### ISSUE TITLE
i get an error while using it

### ISSUE THREAD

**Issue by notkar1m** [lfavole/songs-dl#1]
whenever i run songs-dl "song name" i get this error:

Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\user\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\songs-dl.exe\__main__.py", line 4, in <module>
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\songs_dl\__init__.py", line 19, in <module>
    from .deezer import download_deezer
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\songs_dl\deezer.py", line 11, in <module>
    from .utils import Picture, PictureProvider, Song, format_query, get, locked
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\songs_dl\utils.py", line 9, in <module>
    from typing import Any, Callable, Literal, Required, Sequence, Type, TypedDict, TypeVar, Union, get_origin, overload
ImportError: cannot import name 'Required' from 'typing' (c:\users\user\appdata\local\programs\python\python39\lib\typing.py)  

please i need help.

**Comment by lfavole** [comment]
Hello @Kar1m,
`typing.Required` is only available [as of Python 3.11](https://docs.python.org/3/library/typing.html#typing.Required). Please upgrade to use my program.
Thanks in advance,
Laurent FAVOLE
